name: Scheduled Merge
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: '*/20 * * * *'
      # At every 20th minute.
jobs:
  scheduledmerge:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduling merge
        uses: gr2m/merge-schedule-action@fb456f7b7238899f6e37daa2329c20c558946794 # v2.6.3
        with:
          merge_method: squash
            # merge, squash or rebase.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
